version: '3.8'

services:
  pyro_labeller:
    image: pyro_labeller:latest
    environment:
      - HOST=${HOST}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    restart: always
    ports:
      - 8501:8501


  task_manager:
    image: task_manager:latest
    environment:
      - HOST=${HOST}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - AWS_KEY=${AWS_KEY}
      - AWS_ACC=${AWS_ACC}
    restart: always
 
