version: '3.8'

services:
  pyro-engine:
    image: pyro_labeller:latest
    environment:
      - HOST=${HOST}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    restart: always
    ports:
      - 8501:8501